{
  "checkpoints": [
    "{\n  \"trainable_name\": \"training_function\",\n  \"trial_id\": \"01feb_00002\",\n  \"config\": {\n    \"layer_1_size\": 32,\n    \"layer_2_size\": 64,\n    \"lr\": 0.018446771203643485,\n    \"batch_size\": 32\n  },\n  \"local_dir\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha\",\n  \"evaluated_params\": {\n    \"layer_1_size\": 32,\n    \"layer_2_size\": 64,\n    \"lr\": 0.018446771203643485,\n    \"batch_size\": 32\n  },\n  \"experiment_tag\": \"2_batch_size=32,layer_1_size=32,layer_2_size=64,lr=0.018447\",\n  \"location\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"8005953a000000000000008c0e7261792e74756e652e747269616c948c084c6f636174696f6e9493942981947d94288c08686f73746e616d65944e8c03706964944e75622e\"\n  },\n  \"resources\": {\n    \"cpu\": 6,\n    \"gpu\": 0,\n    \"memory\": 0,\n    \"object_store_memory\": 0,\n    \"extra_cpu\": 0,\n    \"extra_gpu\": 0,\n    \"extra_memory\": 0,\n    \"extra_object_store_memory\": 0,\n    \"custom_resources\": {},\n    \"extra_custom_resources\": {}\n  },\n  \"placement_group_factory\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"800595b2000000000000008c1f7261792e74756e652e7574696c732e706c6163656d656e745f67726f757073948c15506c6163656d656e7447726f7570466163746f72799493942981947d94288c085f62756e646c6573945d947d94288c03435055944b068c03475055944b008c066d656d6f7279944b008c136f626a6563745f73746f72655f6d656d6f7279944b0075618c095f7374726174656779948c045041434b948c055f6172677394298c075f6b7761726773947d9475622e\"\n  },\n  \"stopping_criterion\": {},\n  \"log_to_file\": [\n    null,\n    null\n  ],\n  \"max_failures\": 0,\n  \"last_result\": {},\n  \"last_update_time\": -Infinity,\n  \"metric_analysis\": {},\n  \"n_steps\": [\n    5,\n    10\n  ],\n  \"metric_n_steps\": {},\n  \"export_formats\": [],\n  \"status\": \"ERROR\",\n  \"start_time\": 1621847490.5393422,\n  \"logdir\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha/training_function_01feb_00002_2_batch_size=32,layer_1_size=32,layer_2_size=64,lr=0.018447_2021-05-24_11-11-22\",\n  \"runner\": null,\n  \"last_debug\": 0,\n  \"error_file\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha/training_function_01feb_00002_2_batch_size=32,layer_1_size=32,layer_2_size=64,lr=0.018447_2021-05-24_11-11-22/error.txt\",\n  \"error_msg\": \"Traceback (most recent call last):\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trial_runner.py\\\", line 702, in _process_trial\\n    results = self.trial_executor.fetch_result(trial)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py\\\", line 686, in fetch_result\\n    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/_private/client_mode_hook.py\\\", line 47, in wrapper\\n    return func(*args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/worker.py\\\", line 1481, in get\\n    raise value.as_instanceof_cause()\\nray.exceptions.RayTaskError(TuneError): \\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=52588, ip=192.168.2.103)\\n  File \\\"python/ray/_raylet.pyx\\\", line 505, in ray._raylet.execute_task\\n  File \\\"python/ray/_raylet.pyx\\\", line 449, in ray._raylet.execute_task.function_executor\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/_private/function_manager.py\\\", line 556, in actor_method_executor\\n    return method(__ray_actor, *args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trainable.py\\\", line 173, in train_buffered\\n    result = self.train()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trainable.py\\\", line 232, in train\\n    result = self.step()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 366, in step\\n    self._report_thread_runner_error(block=True)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 512, in _report_thread_runner_error\\n    raise TuneError(\\nray.tune.error.TuneError: Trial raised an exception. Traceback:\\n\\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=52588, ip=192.168.2.103)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 248, in run\\n    self._entrypoint()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 315, in entrypoint\\n    return self._trainable_func(self.config, self._status_reporter,\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 580, in _trainable_func\\n    output = fn()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/utils/trainable.py\\\", line 339, in _inner\\n    inner(config, checkpoint_dir=None)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/utils/trainable.py\\\", line 330, in inner\\n    trainable(config, **fn_kwargs)\\n  File \\\"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/src/Main.py\\\", line 32, in training_function\\n    trainer.fit(model)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 458, in fit\\n    self._run(model)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 756, in _run\\n    self.dispatch()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 797, in dispatch\\n    self.accelerator.start_training(self)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py\\\", line 96, in start_training\\n    self.training_type_plugin.start_training(trainer)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py\\\", line 144, in start_training\\n    self._results = trainer.run_stage()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 807, in run_stage\\n    return self.run_train()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 869, in run_train\\n    self.train_loop.run_training_epoch()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py\\\", line 489, in run_training_epoch\\n    batch_output = self.run_training_batch(batch, batch_idx, dataloader_idx)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py\\\", line 729, in run_training_batch\\n    self.optimizer_step(optimizer, opt_idx, batch_idx, train_step_and_backward_closure)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py\\\", line 424, in optimizer_step\\n    model_ref.optimizer_step(\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/core/lightning.py\\\", line 1403, in optimizer_step\\n    optimizer.step(closure=optimizer_closure)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/core/optimizer.py\\\", line 214, in step\\n    self.__optimizer_step(*args, closure=closure, profiler_name=profiler_name, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/core/optimizer.py\\\", line 134, in __optimizer_step\\n    trainer.accelerator.optimizer_step(optimizer, self._optimizer_idx, lambda_closure=closure, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py\\\", line 329, in optimizer_step\\n    self.run_optimizer_step(optimizer, opt_idx, lambda_closure, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py\\\", line 336, in run_optimizer_step\\n    self.training_type_plugin.optimizer_step(optimizer, lambda_closure=lambda_closure, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py\\\", line 193, in optimizer_step\\n    optimizer.step(closure=lambda_closure, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/torch/optim/optimizer.py\\\", line 89, in wrapper\\n    return func(*args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/torch/autograd/grad_mode.py\\\", line 27, in decorate_context\\n    return func(*args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/torch/optim/adam.py\\\", line 66, in step\\n    loss = closure()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py\\\", line 723, in train_step_and_backward_closure\\n    result = self.training_step_and_backward(\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py\\\", line 812, in training_step_and_backward\\n    result = self.training_step(split_batch, batch_idx, opt_idx, hiddens)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py\\\", line 280, in training_step\\n    training_step_output = self.trainer.accelerator.training_step(args)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py\\\", line 204, in training_step\\n    return self.training_type_plugin.training_step(*args)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py\\\", line 155, in training_step\\n    return self.lightning_module.training_step(*args, **kwargs)\\n  File \\\"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/src/models/LightningMNISTClassifier.py\\\", line 60, in training_step\\n    self.logger.experiment.logParam(self.layer_2_size) #.log_hyperparams(self.layer_1_size)\\nAttributeError: 'MlflowClient' object has no attribute 'logParam'\\n\",\n  \"trial_name_creator\": null,\n  \"custom_trial_name\": null,\n  \"custom_dirname\": null,\n  \"saving_to\": null,\n  \"remote_checkpoint_dir_prefix\": null,\n  \"checkpoint_freq\": 0,\n  \"checkpoint_at_end\": false,\n  \"keep_checkpoints_num\": null,\n  \"checkpoint_score_attr\": \"training_iteration\",\n  \"sync_on_checkpoint\": true,\n  \"checkpoint_manager\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"80059566010000000000008c1b7261792e74756e652e636865636b706f696e745f6d616e61676572948c11436865636b706f696e744d616e616765729493942981947d94288c146b6565705f636865636b706f696e74735f6e756d94477ff00000000000008c165f636865636b706f696e745f73636f72655f6465736394898c165f636865636b706f696e745f73636f72655f61747472948c12747261696e696e675f697465726174696f6e948c1c6e65776573745f70657273697374656e745f636865636b706f696e749468008c0a436865636b706f696e749493942981947d94288c0773746f72616765948c0a70657273697374656e74948c0576616c7565944e8c06726573756c74947d9475628c195f6e65776573745f6d656d6f72795f636865636b706f696e7494680b2981947d9428680e8c066d656d6f72799468104e68117d9475628c115f626573745f636865636b706f696e7473945d948c0b5f6d656d62657273686970948f9475622e\"\n  },\n  \"restore_path\": null,\n  \"restoring_from\": null,\n  \"num_failures\": 1,\n  \"results\": \"80054e2e\",\n  \"best_result\": \"80054e2e\",\n  \"param_config\": \"80054e2e\",\n  \"extra_arg\": \"80054e2e\",\n  \"_state_json\": null,\n  \"_state_valid\": false\n}",
    "{\n  \"trainable_name\": \"training_function\",\n  \"trial_id\": \"01feb_00003\",\n  \"config\": {\n    \"layer_1_size\": 128,\n    \"layer_2_size\": 64,\n    \"lr\": 0.0003481800556027441,\n    \"batch_size\": 64\n  },\n  \"local_dir\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha\",\n  \"evaluated_params\": {\n    \"layer_1_size\": 128,\n    \"layer_2_size\": 64,\n    \"lr\": 0.0003481800556027441,\n    \"batch_size\": 64\n  },\n  \"experiment_tag\": \"3_batch_size=64,layer_1_size=128,layer_2_size=64,lr=0.00034818\",\n  \"location\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"8005953a000000000000008c0e7261792e74756e652e747269616c948c084c6f636174696f6e9493942981947d94288c08686f73746e616d65944e8c03706964944e75622e\"\n  },\n  \"resources\": {\n    \"cpu\": 6,\n    \"gpu\": 0,\n    \"memory\": 0,\n    \"object_store_memory\": 0,\n    \"extra_cpu\": 0,\n    \"extra_gpu\": 0,\n    \"extra_memory\": 0,\n    \"extra_object_store_memory\": 0,\n    \"custom_resources\": {},\n    \"extra_custom_resources\": {}\n  },\n  \"placement_group_factory\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"800595b2000000000000008c1f7261792e74756e652e7574696c732e706c6163656d656e745f67726f757073948c15506c6163656d656e7447726f7570466163746f72799493942981947d94288c085f62756e646c6573945d947d94288c03435055944b068c03475055944b008c066d656d6f7279944b008c136f626a6563745f73746f72655f6d656d6f7279944b0075618c095f7374726174656779948c045041434b948c055f6172677394298c075f6b7761726773947d9475622e\"\n  },\n  \"stopping_criterion\": {},\n  \"log_to_file\": [\n    null,\n    null\n  ],\n  \"max_failures\": 0,\n  \"last_result\": {},\n  \"last_update_time\": -Infinity,\n  \"metric_analysis\": {},\n  \"n_steps\": [\n    5,\n    10\n  ],\n  \"metric_n_steps\": {},\n  \"export_formats\": [],\n  \"status\": \"ERROR\",\n  \"start_time\": 1621847490.5496478,\n  \"logdir\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha/training_function_01feb_00003_3_batch_size=64,layer_1_size=128,layer_2_size=64,lr=0.00034818_2021-05-24_11-11-30\",\n  \"runner\": null,\n  \"last_debug\": 0,\n  \"error_file\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha/training_function_01feb_00003_3_batch_size=64,layer_1_size=128,layer_2_size=64,lr=0.00034818_2021-05-24_11-11-30/error.txt\",\n  \"error_msg\": \"Traceback (most recent call last):\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trial_runner.py\\\", line 702, in _process_trial\\n    results = self.trial_executor.fetch_result(trial)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py\\\", line 686, in fetch_result\\n    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/_private/client_mode_hook.py\\\", line 47, in wrapper\\n    return func(*args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/worker.py\\\", line 1481, in get\\n    raise value.as_instanceof_cause()\\nray.exceptions.RayTaskError(TuneError): \\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=52599, ip=192.168.2.103)\\n  File \\\"python/ray/_raylet.pyx\\\", line 505, in ray._raylet.execute_task\\n  File \\\"python/ray/_raylet.pyx\\\", line 449, in ray._raylet.execute_task.function_executor\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/_private/function_manager.py\\\", line 556, in actor_method_executor\\n    return method(__ray_actor, *args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trainable.py\\\", line 173, in train_buffered\\n    result = self.train()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trainable.py\\\", line 232, in train\\n    result = self.step()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 366, in step\\n    self._report_thread_runner_error(block=True)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 512, in _report_thread_runner_error\\n    raise TuneError(\\nray.tune.error.TuneError: Trial raised an exception. Traceback:\\n\\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=52599, ip=192.168.2.103)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 248, in run\\n    self._entrypoint()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 315, in entrypoint\\n    return self._trainable_func(self.config, self._status_reporter,\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 580, in _trainable_func\\n    output = fn()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/utils/trainable.py\\\", line 339, in _inner\\n    inner(config, checkpoint_dir=None)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/utils/trainable.py\\\", line 330, in inner\\n    trainable(config, **fn_kwargs)\\n  File \\\"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/src/Main.py\\\", line 32, in training_function\\n    trainer.fit(model)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 458, in fit\\n    self._run(model)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 756, in _run\\n    self.dispatch()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 797, in dispatch\\n    self.accelerator.start_training(self)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py\\\", line 96, in start_training\\n    self.training_type_plugin.start_training(trainer)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py\\\", line 144, in start_training\\n    self._results = trainer.run_stage()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 807, in run_stage\\n    return self.run_train()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 869, in run_train\\n    self.train_loop.run_training_epoch()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py\\\", line 489, in run_training_epoch\\n    batch_output = self.run_training_batch(batch, batch_idx, dataloader_idx)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py\\\", line 729, in run_training_batch\\n    self.optimizer_step(optimizer, opt_idx, batch_idx, train_step_and_backward_closure)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py\\\", line 424, in optimizer_step\\n    model_ref.optimizer_step(\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/core/lightning.py\\\", line 1403, in optimizer_step\\n    optimizer.step(closure=optimizer_closure)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/core/optimizer.py\\\", line 214, in step\\n    self.__optimizer_step(*args, closure=closure, profiler_name=profiler_name, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/core/optimizer.py\\\", line 134, in __optimizer_step\\n    trainer.accelerator.optimizer_step(optimizer, self._optimizer_idx, lambda_closure=closure, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py\\\", line 329, in optimizer_step\\n    self.run_optimizer_step(optimizer, opt_idx, lambda_closure, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py\\\", line 336, in run_optimizer_step\\n    self.training_type_plugin.optimizer_step(optimizer, lambda_closure=lambda_closure, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py\\\", line 193, in optimizer_step\\n    optimizer.step(closure=lambda_closure, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/torch/optim/optimizer.py\\\", line 89, in wrapper\\n    return func(*args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/torch/autograd/grad_mode.py\\\", line 27, in decorate_context\\n    return func(*args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/torch/optim/adam.py\\\", line 66, in step\\n    loss = closure()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py\\\", line 723, in train_step_and_backward_closure\\n    result = self.training_step_and_backward(\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py\\\", line 812, in training_step_and_backward\\n    result = self.training_step(split_batch, batch_idx, opt_idx, hiddens)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py\\\", line 280, in training_step\\n    training_step_output = self.trainer.accelerator.training_step(args)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py\\\", line 204, in training_step\\n    return self.training_type_plugin.training_step(*args)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py\\\", line 155, in training_step\\n    return self.lightning_module.training_step(*args, **kwargs)\\n  File \\\"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/src/models/LightningMNISTClassifier.py\\\", line 60, in training_step\\n    self.logger.experiment.logParam(self.layer_2_size) #.log_hyperparams(self.layer_1_size)\\nAttributeError: 'MlflowClient' object has no attribute 'logParam'\\n\",\n  \"trial_name_creator\": null,\n  \"custom_trial_name\": null,\n  \"custom_dirname\": null,\n  \"saving_to\": null,\n  \"remote_checkpoint_dir_prefix\": null,\n  \"checkpoint_freq\": 0,\n  \"checkpoint_at_end\": false,\n  \"keep_checkpoints_num\": null,\n  \"checkpoint_score_attr\": \"training_iteration\",\n  \"sync_on_checkpoint\": true,\n  \"checkpoint_manager\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"80059566010000000000008c1b7261792e74756e652e636865636b706f696e745f6d616e61676572948c11436865636b706f696e744d616e616765729493942981947d94288c146b6565705f636865636b706f696e74735f6e756d94477ff00000000000008c165f636865636b706f696e745f73636f72655f6465736394898c165f636865636b706f696e745f73636f72655f61747472948c12747261696e696e675f697465726174696f6e948c1c6e65776573745f70657273697374656e745f636865636b706f696e749468008c0a436865636b706f696e749493942981947d94288c0773746f72616765948c0a70657273697374656e74948c0576616c7565944e8c06726573756c74947d9475628c195f6e65776573745f6d656d6f72795f636865636b706f696e7494680b2981947d9428680e8c066d656d6f72799468104e68117d9475628c115f626573745f636865636b706f696e7473945d948c0b5f6d656d62657273686970948f9475622e\"\n  },\n  \"restore_path\": null,\n  \"restoring_from\": null,\n  \"num_failures\": 1,\n  \"results\": \"80054e2e\",\n  \"best_result\": \"80054e2e\",\n  \"param_config\": \"80054e2e\",\n  \"extra_arg\": \"80054e2e\",\n  \"_state_json\": null,\n  \"_state_valid\": false\n}",
    "{\n  \"trainable_name\": \"training_function\",\n  \"trial_id\": \"01feb_00000\",\n  \"config\": {\n    \"layer_1_size\": 64,\n    \"layer_2_size\": 64,\n    \"lr\": 0.00028258324882055123,\n    \"batch_size\": 128\n  },\n  \"local_dir\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha\",\n  \"evaluated_params\": {\n    \"layer_1_size\": 64,\n    \"layer_2_size\": 64,\n    \"lr\": 0.00028258324882055123,\n    \"batch_size\": 128\n  },\n  \"experiment_tag\": \"0_batch_size=128,layer_1_size=64,layer_2_size=64,lr=0.00028258\",\n  \"location\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"8005953a000000000000008c0e7261792e74756e652e747269616c948c084c6f636174696f6e9493942981947d94288c08686f73746e616d65944e8c03706964944e75622e\"\n  },\n  \"resources\": {\n    \"cpu\": 6,\n    \"gpu\": 0,\n    \"memory\": 0,\n    \"object_store_memory\": 0,\n    \"extra_cpu\": 0,\n    \"extra_gpu\": 0,\n    \"extra_memory\": 0,\n    \"extra_object_store_memory\": 0,\n    \"custom_resources\": {},\n    \"extra_custom_resources\": {}\n  },\n  \"placement_group_factory\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"800595b2000000000000008c1f7261792e74756e652e7574696c732e706c6163656d656e745f67726f757073948c15506c6163656d656e7447726f7570466163746f72799493942981947d94288c085f62756e646c6573945d947d94288c03435055944b068c03475055944b008c066d656d6f7279944b008c136f626a6563745f73746f72655f6d656d6f7279944b0075618c095f7374726174656779948c045041434b948c055f6172677394298c075f6b7761726773947d9475622e\"\n  },\n  \"stopping_criterion\": {},\n  \"log_to_file\": [\n    null,\n    null\n  ],\n  \"max_failures\": 0,\n  \"last_result\": {},\n  \"last_update_time\": -Infinity,\n  \"metric_analysis\": {},\n  \"n_steps\": [\n    5,\n    10\n  ],\n  \"metric_n_steps\": {},\n  \"export_formats\": [],\n  \"status\": \"ERROR\",\n  \"start_time\": 1621847482.247315,\n  \"logdir\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha/training_function_01feb_00000_0_batch_size=128,layer_1_size=64,layer_2_size=64,lr=0.00028258_2021-05-24_11-11-22\",\n  \"runner\": null,\n  \"last_debug\": 0,\n  \"error_file\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha/training_function_01feb_00000_0_batch_size=128,layer_1_size=64,layer_2_size=64,lr=0.00028258_2021-05-24_11-11-22/error.txt\",\n  \"error_msg\": \"Traceback (most recent call last):\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trial_runner.py\\\", line 702, in _process_trial\\n    results = self.trial_executor.fetch_result(trial)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py\\\", line 686, in fetch_result\\n    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/_private/client_mode_hook.py\\\", line 47, in wrapper\\n    return func(*args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/worker.py\\\", line 1481, in get\\n    raise value.as_instanceof_cause()\\nray.exceptions.RayTaskError(TuneError): \\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=52600, ip=192.168.2.103)\\n  File \\\"python/ray/_raylet.pyx\\\", line 505, in ray._raylet.execute_task\\n  File \\\"python/ray/_raylet.pyx\\\", line 449, in ray._raylet.execute_task.function_executor\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/_private/function_manager.py\\\", line 556, in actor_method_executor\\n    return method(__ray_actor, *args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trainable.py\\\", line 173, in train_buffered\\n    result = self.train()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trainable.py\\\", line 232, in train\\n    result = self.step()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 366, in step\\n    self._report_thread_runner_error(block=True)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 512, in _report_thread_runner_error\\n    raise TuneError(\\nray.tune.error.TuneError: Trial raised an exception. Traceback:\\n\\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=52600, ip=192.168.2.103)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 248, in run\\n    self._entrypoint()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 315, in entrypoint\\n    return self._trainable_func(self.config, self._status_reporter,\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 580, in _trainable_func\\n    output = fn()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/utils/trainable.py\\\", line 339, in _inner\\n    inner(config, checkpoint_dir=None)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/utils/trainable.py\\\", line 330, in inner\\n    trainable(config, **fn_kwargs)\\n  File \\\"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/src/Main.py\\\", line 32, in training_function\\n    trainer.fit(model)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 458, in fit\\n    self._run(model)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 756, in _run\\n    self.dispatch()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 797, in dispatch\\n    self.accelerator.start_training(self)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py\\\", line 96, in start_training\\n    self.training_type_plugin.start_training(trainer)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py\\\", line 144, in start_training\\n    self._results = trainer.run_stage()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 807, in run_stage\\n    return self.run_train()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 869, in run_train\\n    self.train_loop.run_training_epoch()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py\\\", line 489, in run_training_epoch\\n    batch_output = self.run_training_batch(batch, batch_idx, dataloader_idx)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py\\\", line 729, in run_training_batch\\n    self.optimizer_step(optimizer, opt_idx, batch_idx, train_step_and_backward_closure)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py\\\", line 424, in optimizer_step\\n    model_ref.optimizer_step(\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/core/lightning.py\\\", line 1403, in optimizer_step\\n    optimizer.step(closure=optimizer_closure)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/core/optimizer.py\\\", line 214, in step\\n    self.__optimizer_step(*args, closure=closure, profiler_name=profiler_name, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/core/optimizer.py\\\", line 134, in __optimizer_step\\n    trainer.accelerator.optimizer_step(optimizer, self._optimizer_idx, lambda_closure=closure, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py\\\", line 329, in optimizer_step\\n    self.run_optimizer_step(optimizer, opt_idx, lambda_closure, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py\\\", line 336, in run_optimizer_step\\n    self.training_type_plugin.optimizer_step(optimizer, lambda_closure=lambda_closure, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py\\\", line 193, in optimizer_step\\n    optimizer.step(closure=lambda_closure, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/torch/optim/optimizer.py\\\", line 89, in wrapper\\n    return func(*args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/torch/autograd/grad_mode.py\\\", line 27, in decorate_context\\n    return func(*args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/torch/optim/adam.py\\\", line 66, in step\\n    loss = closure()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py\\\", line 723, in train_step_and_backward_closure\\n    result = self.training_step_and_backward(\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py\\\", line 812, in training_step_and_backward\\n    result = self.training_step(split_batch, batch_idx, opt_idx, hiddens)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py\\\", line 280, in training_step\\n    training_step_output = self.trainer.accelerator.training_step(args)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py\\\", line 204, in training_step\\n    return self.training_type_plugin.training_step(*args)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py\\\", line 155, in training_step\\n    return self.lightning_module.training_step(*args, **kwargs)\\n  File \\\"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/src/models/LightningMNISTClassifier.py\\\", line 60, in training_step\\n    self.logger.experiment.logParam(self.layer_2_size) #.log_hyperparams(self.layer_1_size)\\nAttributeError: 'MlflowClient' object has no attribute 'logParam'\\n\",\n  \"trial_name_creator\": null,\n  \"custom_trial_name\": null,\n  \"custom_dirname\": null,\n  \"saving_to\": null,\n  \"remote_checkpoint_dir_prefix\": null,\n  \"checkpoint_freq\": 0,\n  \"checkpoint_at_end\": false,\n  \"keep_checkpoints_num\": null,\n  \"checkpoint_score_attr\": \"training_iteration\",\n  \"sync_on_checkpoint\": true,\n  \"checkpoint_manager\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"80059566010000000000008c1b7261792e74756e652e636865636b706f696e745f6d616e61676572948c11436865636b706f696e744d616e616765729493942981947d94288c146b6565705f636865636b706f696e74735f6e756d94477ff00000000000008c165f636865636b706f696e745f73636f72655f6465736394898c165f636865636b706f696e745f73636f72655f61747472948c12747261696e696e675f697465726174696f6e948c1c6e65776573745f70657273697374656e745f636865636b706f696e749468008c0a436865636b706f696e749493942981947d94288c0773746f72616765948c0a70657273697374656e74948c0576616c7565944e8c06726573756c74947d9475628c195f6e65776573745f6d656d6f72795f636865636b706f696e7494680b2981947d9428680e8c066d656d6f72799468104e68117d9475628c115f626573745f636865636b706f696e7473945d948c0b5f6d656d62657273686970948f9475622e\"\n  },\n  \"restore_path\": null,\n  \"restoring_from\": null,\n  \"num_failures\": 1,\n  \"results\": \"80054e2e\",\n  \"best_result\": \"80054e2e\",\n  \"param_config\": \"80054e2e\",\n  \"extra_arg\": \"80054e2e\",\n  \"_state_json\": null,\n  \"_state_valid\": false\n}",
    "{\n  \"trainable_name\": \"training_function\",\n  \"trial_id\": \"01feb_00007\",\n  \"config\": {\n    \"layer_1_size\": 64,\n    \"layer_2_size\": 128,\n    \"lr\": 0.014292606380881355,\n    \"batch_size\": 64\n  },\n  \"local_dir\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha\",\n  \"evaluated_params\": {\n    \"layer_1_size\": 64,\n    \"layer_2_size\": 128,\n    \"lr\": 0.014292606380881355,\n    \"batch_size\": 64\n  },\n  \"experiment_tag\": \"7_batch_size=64,layer_1_size=64,layer_2_size=128,lr=0.014293\",\n  \"location\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"8005953a000000000000008c0e7261792e74756e652e747269616c948c084c6f636174696f6e9493942981947d94288c08686f73746e616d65944e8c03706964944e75622e\"\n  },\n  \"resources\": {\n    \"cpu\": 6,\n    \"gpu\": 0,\n    \"memory\": 0,\n    \"object_store_memory\": 0,\n    \"extra_cpu\": 0,\n    \"extra_gpu\": 0,\n    \"extra_memory\": 0,\n    \"extra_object_store_memory\": 0,\n    \"custom_resources\": {},\n    \"extra_custom_resources\": {}\n  },\n  \"placement_group_factory\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"800595b2000000000000008c1f7261792e74756e652e7574696c732e706c6163656d656e745f67726f757073948c15506c6163656d656e7447726f7570466163746f72799493942981947d94288c085f62756e646c6573945d947d94288c03435055944b068c03475055944b008c066d656d6f7279944b008c136f626a6563745f73746f72655f6d656d6f7279944b0075618c095f7374726174656779948c045041434b948c055f6172677394298c075f6b7761726773947d9475622e\"\n  },\n  \"stopping_criterion\": {},\n  \"log_to_file\": [\n    null,\n    null\n  ],\n  \"max_failures\": 0,\n  \"last_result\": {},\n  \"last_update_time\": -Infinity,\n  \"metric_analysis\": {},\n  \"n_steps\": [\n    5,\n    10\n  ],\n  \"metric_n_steps\": {},\n  \"export_formats\": [],\n  \"status\": \"ERROR\",\n  \"start_time\": 1621847506.930032,\n  \"logdir\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha/training_function_01feb_00007_7_batch_size=64,layer_1_size=64,layer_2_size=128,lr=0.014293_2021-05-24_11-11-46\",\n  \"runner\": null,\n  \"last_debug\": 0,\n  \"error_file\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha/training_function_01feb_00007_7_batch_size=64,layer_1_size=64,layer_2_size=128,lr=0.014293_2021-05-24_11-11-46/error.txt\",\n  \"error_msg\": \"Traceback (most recent call last):\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trial_runner.py\\\", line 702, in _process_trial\\n    results = self.trial_executor.fetch_result(trial)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py\\\", line 686, in fetch_result\\n    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/_private/client_mode_hook.py\\\", line 47, in wrapper\\n    return func(*args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/worker.py\\\", line 1481, in get\\n    raise value.as_instanceof_cause()\\nray.exceptions.RayTaskError(TuneError): \\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=52593, ip=192.168.2.103)\\n  File \\\"python/ray/_raylet.pyx\\\", line 505, in ray._raylet.execute_task\\n  File \\\"python/ray/_raylet.pyx\\\", line 449, in ray._raylet.execute_task.function_executor\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/_private/function_manager.py\\\", line 556, in actor_method_executor\\n    return method(__ray_actor, *args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trainable.py\\\", line 173, in train_buffered\\n    result = self.train()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trainable.py\\\", line 232, in train\\n    result = self.step()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 366, in step\\n    self._report_thread_runner_error(block=True)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 512, in _report_thread_runner_error\\n    raise TuneError(\\nray.tune.error.TuneError: Trial raised an exception. Traceback:\\n\\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=52593, ip=192.168.2.103)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 248, in run\\n    self._entrypoint()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 315, in entrypoint\\n    return self._trainable_func(self.config, self._status_reporter,\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 580, in _trainable_func\\n    output = fn()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/utils/trainable.py\\\", line 339, in _inner\\n    inner(config, checkpoint_dir=None)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/utils/trainable.py\\\", line 330, in inner\\n    trainable(config, **fn_kwargs)\\n  File \\\"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/src/Main.py\\\", line 32, in training_function\\n    trainer.fit(model)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 458, in fit\\n    self._run(model)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 756, in _run\\n    self.dispatch()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 797, in dispatch\\n    self.accelerator.start_training(self)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py\\\", line 96, in start_training\\n    self.training_type_plugin.start_training(trainer)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py\\\", line 144, in start_training\\n    self._results = trainer.run_stage()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 807, in run_stage\\n    return self.run_train()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 869, in run_train\\n    self.train_loop.run_training_epoch()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py\\\", line 489, in run_training_epoch\\n    batch_output = self.run_training_batch(batch, batch_idx, dataloader_idx)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py\\\", line 729, in run_training_batch\\n    self.optimizer_step(optimizer, opt_idx, batch_idx, train_step_and_backward_closure)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py\\\", line 424, in optimizer_step\\n    model_ref.optimizer_step(\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/core/lightning.py\\\", line 1403, in optimizer_step\\n    optimizer.step(closure=optimizer_closure)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/core/optimizer.py\\\", line 214, in step\\n    self.__optimizer_step(*args, closure=closure, profiler_name=profiler_name, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/core/optimizer.py\\\", line 134, in __optimizer_step\\n    trainer.accelerator.optimizer_step(optimizer, self._optimizer_idx, lambda_closure=closure, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py\\\", line 329, in optimizer_step\\n    self.run_optimizer_step(optimizer, opt_idx, lambda_closure, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py\\\", line 336, in run_optimizer_step\\n    self.training_type_plugin.optimizer_step(optimizer, lambda_closure=lambda_closure, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py\\\", line 193, in optimizer_step\\n    optimizer.step(closure=lambda_closure, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/torch/optim/optimizer.py\\\", line 89, in wrapper\\n    return func(*args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/torch/autograd/grad_mode.py\\\", line 27, in decorate_context\\n    return func(*args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/torch/optim/adam.py\\\", line 66, in step\\n    loss = closure()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py\\\", line 723, in train_step_and_backward_closure\\n    result = self.training_step_and_backward(\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py\\\", line 812, in training_step_and_backward\\n    result = self.training_step(split_batch, batch_idx, opt_idx, hiddens)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py\\\", line 280, in training_step\\n    training_step_output = self.trainer.accelerator.training_step(args)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py\\\", line 204, in training_step\\n    return self.training_type_plugin.training_step(*args)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py\\\", line 155, in training_step\\n    return self.lightning_module.training_step(*args, **kwargs)\\n  File \\\"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/src/models/LightningMNISTClassifier.py\\\", line 60, in training_step\\n    self.logger.experiment.logParam(self.layer_2_size) #.log_hyperparams(self.layer_1_size)\\nAttributeError: 'MlflowClient' object has no attribute 'logParam'\\n\",\n  \"trial_name_creator\": null,\n  \"custom_trial_name\": null,\n  \"custom_dirname\": null,\n  \"saving_to\": null,\n  \"remote_checkpoint_dir_prefix\": null,\n  \"checkpoint_freq\": 0,\n  \"checkpoint_at_end\": false,\n  \"keep_checkpoints_num\": null,\n  \"checkpoint_score_attr\": \"training_iteration\",\n  \"sync_on_checkpoint\": true,\n  \"checkpoint_manager\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"80059566010000000000008c1b7261792e74756e652e636865636b706f696e745f6d616e61676572948c11436865636b706f696e744d616e616765729493942981947d94288c146b6565705f636865636b706f696e74735f6e756d94477ff00000000000008c165f636865636b706f696e745f73636f72655f6465736394898c165f636865636b706f696e745f73636f72655f61747472948c12747261696e696e675f697465726174696f6e948c1c6e65776573745f70657273697374656e745f636865636b706f696e749468008c0a436865636b706f696e749493942981947d94288c0773746f72616765948c0a70657273697374656e74948c0576616c7565944e8c06726573756c74947d9475628c195f6e65776573745f6d656d6f72795f636865636b706f696e7494680b2981947d9428680e8c066d656d6f72799468104e68117d9475628c115f626573745f636865636b706f696e7473945d948c0b5f6d656d62657273686970948f9475622e\"\n  },\n  \"restore_path\": null,\n  \"restoring_from\": null,\n  \"num_failures\": 1,\n  \"results\": \"80054e2e\",\n  \"best_result\": \"80054e2e\",\n  \"param_config\": \"80054e2e\",\n  \"extra_arg\": \"80054e2e\",\n  \"_state_json\": null,\n  \"_state_valid\": false\n}",
    "{\n  \"trainable_name\": \"training_function\",\n  \"trial_id\": \"01feb_00005\",\n  \"config\": {\n    \"layer_1_size\": 32,\n    \"layer_2_size\": 64,\n    \"lr\": 0.010055602070938302,\n    \"batch_size\": 32\n  },\n  \"local_dir\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha\",\n  \"evaluated_params\": {\n    \"layer_1_size\": 32,\n    \"layer_2_size\": 64,\n    \"lr\": 0.010055602070938302,\n    \"batch_size\": 32\n  },\n  \"experiment_tag\": \"5_batch_size=32,layer_1_size=32,layer_2_size=64,lr=0.010056\",\n  \"location\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"8005953a000000000000008c0e7261792e74756e652e747269616c948c084c6f636174696f6e9493942981947d94288c08686f73746e616d65944e8c03706964944e75622e\"\n  },\n  \"resources\": {\n    \"cpu\": 6,\n    \"gpu\": 0,\n    \"memory\": 0,\n    \"object_store_memory\": 0,\n    \"extra_cpu\": 0,\n    \"extra_gpu\": 0,\n    \"extra_memory\": 0,\n    \"extra_object_store_memory\": 0,\n    \"custom_resources\": {},\n    \"extra_custom_resources\": {}\n  },\n  \"placement_group_factory\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"800595b2000000000000008c1f7261792e74756e652e7574696c732e706c6163656d656e745f67726f757073948c15506c6163656d656e7447726f7570466163746f72799493942981947d94288c085f62756e646c6573945d947d94288c03435055944b068c03475055944b008c066d656d6f7279944b008c136f626a6563745f73746f72655f6d656d6f7279944b0075618c095f7374726174656779948c045041434b948c055f6172677394298c075f6b7761726773947d9475622e\"\n  },\n  \"stopping_criterion\": {},\n  \"log_to_file\": [\n    null,\n    null\n  ],\n  \"max_failures\": 0,\n  \"last_result\": {},\n  \"last_update_time\": -Infinity,\n  \"metric_analysis\": {},\n  \"n_steps\": [\n    5,\n    10\n  ],\n  \"metric_n_steps\": {},\n  \"export_formats\": [],\n  \"status\": \"ERROR\",\n  \"start_time\": 1621847498.828574,\n  \"logdir\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha/training_function_01feb_00005_5_batch_size=32,layer_1_size=32,layer_2_size=64,lr=0.010056_2021-05-24_11-11-38\",\n  \"runner\": null,\n  \"last_debug\": 0,\n  \"error_file\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha/training_function_01feb_00005_5_batch_size=32,layer_1_size=32,layer_2_size=64,lr=0.010056_2021-05-24_11-11-38/error.txt\",\n  \"error_msg\": \"Traceback (most recent call last):\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trial_runner.py\\\", line 702, in _process_trial\\n    results = self.trial_executor.fetch_result(trial)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py\\\", line 686, in fetch_result\\n    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/_private/client_mode_hook.py\\\", line 47, in wrapper\\n    return func(*args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/worker.py\\\", line 1481, in get\\n    raise value.as_instanceof_cause()\\nray.exceptions.RayTaskError(TuneError): \\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=52598, ip=192.168.2.103)\\n  File \\\"python/ray/_raylet.pyx\\\", line 505, in ray._raylet.execute_task\\n  File \\\"python/ray/_raylet.pyx\\\", line 449, in ray._raylet.execute_task.function_executor\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/_private/function_manager.py\\\", line 556, in actor_method_executor\\n    return method(__ray_actor, *args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trainable.py\\\", line 173, in train_buffered\\n    result = self.train()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trainable.py\\\", line 232, in train\\n    result = self.step()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 366, in step\\n    self._report_thread_runner_error(block=True)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 512, in _report_thread_runner_error\\n    raise TuneError(\\nray.tune.error.TuneError: Trial raised an exception. Traceback:\\n\\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=52598, ip=192.168.2.103)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 248, in run\\n    self._entrypoint()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 315, in entrypoint\\n    return self._trainable_func(self.config, self._status_reporter,\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 580, in _trainable_func\\n    output = fn()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/utils/trainable.py\\\", line 339, in _inner\\n    inner(config, checkpoint_dir=None)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/utils/trainable.py\\\", line 330, in inner\\n    trainable(config, **fn_kwargs)\\n  File \\\"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/src/Main.py\\\", line 32, in training_function\\n    trainer.fit(model)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 458, in fit\\n    self._run(model)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 756, in _run\\n    self.dispatch()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 797, in dispatch\\n    self.accelerator.start_training(self)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py\\\", line 96, in start_training\\n    self.training_type_plugin.start_training(trainer)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py\\\", line 144, in start_training\\n    self._results = trainer.run_stage()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 807, in run_stage\\n    return self.run_train()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 869, in run_train\\n    self.train_loop.run_training_epoch()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py\\\", line 489, in run_training_epoch\\n    batch_output = self.run_training_batch(batch, batch_idx, dataloader_idx)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py\\\", line 729, in run_training_batch\\n    self.optimizer_step(optimizer, opt_idx, batch_idx, train_step_and_backward_closure)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py\\\", line 424, in optimizer_step\\n    model_ref.optimizer_step(\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/core/lightning.py\\\", line 1403, in optimizer_step\\n    optimizer.step(closure=optimizer_closure)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/core/optimizer.py\\\", line 214, in step\\n    self.__optimizer_step(*args, closure=closure, profiler_name=profiler_name, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/core/optimizer.py\\\", line 134, in __optimizer_step\\n    trainer.accelerator.optimizer_step(optimizer, self._optimizer_idx, lambda_closure=closure, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py\\\", line 329, in optimizer_step\\n    self.run_optimizer_step(optimizer, opt_idx, lambda_closure, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py\\\", line 336, in run_optimizer_step\\n    self.training_type_plugin.optimizer_step(optimizer, lambda_closure=lambda_closure, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py\\\", line 193, in optimizer_step\\n    optimizer.step(closure=lambda_closure, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/torch/optim/optimizer.py\\\", line 89, in wrapper\\n    return func(*args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/torch/autograd/grad_mode.py\\\", line 27, in decorate_context\\n    return func(*args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/torch/optim/adam.py\\\", line 66, in step\\n    loss = closure()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py\\\", line 723, in train_step_and_backward_closure\\n    result = self.training_step_and_backward(\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py\\\", line 812, in training_step_and_backward\\n    result = self.training_step(split_batch, batch_idx, opt_idx, hiddens)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py\\\", line 280, in training_step\\n    training_step_output = self.trainer.accelerator.training_step(args)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py\\\", line 204, in training_step\\n    return self.training_type_plugin.training_step(*args)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py\\\", line 155, in training_step\\n    return self.lightning_module.training_step(*args, **kwargs)\\n  File \\\"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/src/models/LightningMNISTClassifier.py\\\", line 60, in training_step\\n    self.logger.experiment.logParam(self.layer_2_size) #.log_hyperparams(self.layer_1_size)\\nAttributeError: 'MlflowClient' object has no attribute 'logParam'\\n\",\n  \"trial_name_creator\": null,\n  \"custom_trial_name\": null,\n  \"custom_dirname\": null,\n  \"saving_to\": null,\n  \"remote_checkpoint_dir_prefix\": null,\n  \"checkpoint_freq\": 0,\n  \"checkpoint_at_end\": false,\n  \"keep_checkpoints_num\": null,\n  \"checkpoint_score_attr\": \"training_iteration\",\n  \"sync_on_checkpoint\": true,\n  \"checkpoint_manager\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"80059566010000000000008c1b7261792e74756e652e636865636b706f696e745f6d616e61676572948c11436865636b706f696e744d616e616765729493942981947d94288c146b6565705f636865636b706f696e74735f6e756d94477ff00000000000008c165f636865636b706f696e745f73636f72655f6465736394898c165f636865636b706f696e745f73636f72655f61747472948c12747261696e696e675f697465726174696f6e948c1c6e65776573745f70657273697374656e745f636865636b706f696e749468008c0a436865636b706f696e749493942981947d94288c0773746f72616765948c0a70657273697374656e74948c0576616c7565944e8c06726573756c74947d9475628c195f6e65776573745f6d656d6f72795f636865636b706f696e7494680b2981947d9428680e8c066d656d6f72799468104e68117d9475628c115f626573745f636865636b706f696e7473945d948c0b5f6d656d62657273686970948f9475622e\"\n  },\n  \"restore_path\": null,\n  \"restoring_from\": null,\n  \"num_failures\": 1,\n  \"results\": \"80054e2e\",\n  \"best_result\": \"80054e2e\",\n  \"param_config\": \"80054e2e\",\n  \"extra_arg\": \"80054e2e\",\n  \"_state_json\": null,\n  \"_state_valid\": false\n}",
    "{\n  \"trainable_name\": \"training_function\",\n  \"trial_id\": \"01feb_00009\",\n  \"config\": {\n    \"layer_1_size\": 64,\n    \"layer_2_size\": 128,\n    \"lr\": 0.08389946698103506,\n    \"batch_size\": 128\n  },\n  \"local_dir\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha\",\n  \"evaluated_params\": {\n    \"layer_1_size\": 64,\n    \"layer_2_size\": 128,\n    \"lr\": 0.08389946698103506,\n    \"batch_size\": 128\n  },\n  \"experiment_tag\": \"9_batch_size=128,layer_1_size=64,layer_2_size=128,lr=0.083899\",\n  \"location\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"8005953a000000000000008c0e7261792e74756e652e747269616c948c084c6f636174696f6e9493942981947d94288c08686f73746e616d65944e8c03706964944e75622e\"\n  },\n  \"resources\": {\n    \"cpu\": 6,\n    \"gpu\": 0,\n    \"memory\": 0,\n    \"object_store_memory\": 0,\n    \"extra_cpu\": 0,\n    \"extra_gpu\": 0,\n    \"extra_memory\": 0,\n    \"extra_object_store_memory\": 0,\n    \"custom_resources\": {},\n    \"extra_custom_resources\": {}\n  },\n  \"placement_group_factory\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"800595b2000000000000008c1f7261792e74756e652e7574696c732e706c6163656d656e745f67726f757073948c15506c6163656d656e7447726f7570466163746f72799493942981947d94288c085f62756e646c6573945d947d94288c03435055944b068c03475055944b008c066d656d6f7279944b008c136f626a6563745f73746f72655f6d656d6f7279944b0075618c095f7374726174656779948c045041434b948c055f6172677394298c075f6b7761726773947d9475622e\"\n  },\n  \"stopping_criterion\": {},\n  \"log_to_file\": [\n    null,\n    null\n  ],\n  \"max_failures\": 0,\n  \"last_result\": {},\n  \"last_update_time\": -Infinity,\n  \"metric_analysis\": {},\n  \"n_steps\": [\n    5,\n    10\n  ],\n  \"metric_n_steps\": {},\n  \"export_formats\": [],\n  \"status\": \"ERROR\",\n  \"start_time\": 1621847515.2692878,\n  \"logdir\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha/training_function_01feb_00009_9_batch_size=128,layer_1_size=64,layer_2_size=128,lr=0.083899_2021-05-24_11-11-55\",\n  \"runner\": null,\n  \"last_debug\": 0,\n  \"error_file\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha/training_function_01feb_00009_9_batch_size=128,layer_1_size=64,layer_2_size=128,lr=0.083899_2021-05-24_11-11-55/error.txt\",\n  \"error_msg\": \"Traceback (most recent call last):\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trial_runner.py\\\", line 702, in _process_trial\\n    results = self.trial_executor.fetch_result(trial)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py\\\", line 686, in fetch_result\\n    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/_private/client_mode_hook.py\\\", line 47, in wrapper\\n    return func(*args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/worker.py\\\", line 1481, in get\\n    raise value.as_instanceof_cause()\\nray.exceptions.RayTaskError(TuneError): \\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=52594, ip=192.168.2.103)\\n  File \\\"python/ray/_raylet.pyx\\\", line 505, in ray._raylet.execute_task\\n  File \\\"python/ray/_raylet.pyx\\\", line 449, in ray._raylet.execute_task.function_executor\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/_private/function_manager.py\\\", line 556, in actor_method_executor\\n    return method(__ray_actor, *args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trainable.py\\\", line 173, in train_buffered\\n    result = self.train()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trainable.py\\\", line 232, in train\\n    result = self.step()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 366, in step\\n    self._report_thread_runner_error(block=True)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 512, in _report_thread_runner_error\\n    raise TuneError(\\nray.tune.error.TuneError: Trial raised an exception. Traceback:\\n\\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=52594, ip=192.168.2.103)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 248, in run\\n    self._entrypoint()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 315, in entrypoint\\n    return self._trainable_func(self.config, self._status_reporter,\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 580, in _trainable_func\\n    output = fn()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/utils/trainable.py\\\", line 339, in _inner\\n    inner(config, checkpoint_dir=None)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/utils/trainable.py\\\", line 330, in inner\\n    trainable(config, **fn_kwargs)\\n  File \\\"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/src/Main.py\\\", line 32, in training_function\\n    trainer.fit(model)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 458, in fit\\n    self._run(model)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 756, in _run\\n    self.dispatch()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 797, in dispatch\\n    self.accelerator.start_training(self)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py\\\", line 96, in start_training\\n    self.training_type_plugin.start_training(trainer)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py\\\", line 144, in start_training\\n    self._results = trainer.run_stage()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 807, in run_stage\\n    return self.run_train()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 869, in run_train\\n    self.train_loop.run_training_epoch()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py\\\", line 489, in run_training_epoch\\n    batch_output = self.run_training_batch(batch, batch_idx, dataloader_idx)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py\\\", line 729, in run_training_batch\\n    self.optimizer_step(optimizer, opt_idx, batch_idx, train_step_and_backward_closure)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py\\\", line 424, in optimizer_step\\n    model_ref.optimizer_step(\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/core/lightning.py\\\", line 1403, in optimizer_step\\n    optimizer.step(closure=optimizer_closure)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/core/optimizer.py\\\", line 214, in step\\n    self.__optimizer_step(*args, closure=closure, profiler_name=profiler_name, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/core/optimizer.py\\\", line 134, in __optimizer_step\\n    trainer.accelerator.optimizer_step(optimizer, self._optimizer_idx, lambda_closure=closure, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py\\\", line 329, in optimizer_step\\n    self.run_optimizer_step(optimizer, opt_idx, lambda_closure, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py\\\", line 336, in run_optimizer_step\\n    self.training_type_plugin.optimizer_step(optimizer, lambda_closure=lambda_closure, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py\\\", line 193, in optimizer_step\\n    optimizer.step(closure=lambda_closure, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/torch/optim/optimizer.py\\\", line 89, in wrapper\\n    return func(*args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/torch/autograd/grad_mode.py\\\", line 27, in decorate_context\\n    return func(*args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/torch/optim/adam.py\\\", line 66, in step\\n    loss = closure()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py\\\", line 723, in train_step_and_backward_closure\\n    result = self.training_step_and_backward(\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py\\\", line 812, in training_step_and_backward\\n    result = self.training_step(split_batch, batch_idx, opt_idx, hiddens)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py\\\", line 280, in training_step\\n    training_step_output = self.trainer.accelerator.training_step(args)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py\\\", line 204, in training_step\\n    return self.training_type_plugin.training_step(*args)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py\\\", line 155, in training_step\\n    return self.lightning_module.training_step(*args, **kwargs)\\n  File \\\"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/src/models/LightningMNISTClassifier.py\\\", line 60, in training_step\\n    self.logger.experiment.logParam(self.layer_2_size) #.log_hyperparams(self.layer_1_size)\\nAttributeError: 'MlflowClient' object has no attribute 'logParam'\\n\",\n  \"trial_name_creator\": null,\n  \"custom_trial_name\": null,\n  \"custom_dirname\": null,\n  \"saving_to\": null,\n  \"remote_checkpoint_dir_prefix\": null,\n  \"checkpoint_freq\": 0,\n  \"checkpoint_at_end\": false,\n  \"keep_checkpoints_num\": null,\n  \"checkpoint_score_attr\": \"training_iteration\",\n  \"sync_on_checkpoint\": true,\n  \"checkpoint_manager\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"80059566010000000000008c1b7261792e74756e652e636865636b706f696e745f6d616e61676572948c11436865636b706f696e744d616e616765729493942981947d94288c146b6565705f636865636b706f696e74735f6e756d94477ff00000000000008c165f636865636b706f696e745f73636f72655f6465736394898c165f636865636b706f696e745f73636f72655f61747472948c12747261696e696e675f697465726174696f6e948c1c6e65776573745f70657273697374656e745f636865636b706f696e749468008c0a436865636b706f696e749493942981947d94288c0773746f72616765948c0a70657273697374656e74948c0576616c7565944e8c06726573756c74947d9475628c195f6e65776573745f6d656d6f72795f636865636b706f696e7494680b2981947d9428680e8c066d656d6f72799468104e68117d9475628c115f626573745f636865636b706f696e7473945d948c0b5f6d656d62657273686970948f9475622e\"\n  },\n  \"restore_path\": null,\n  \"restoring_from\": null,\n  \"num_failures\": 1,\n  \"results\": \"80054e2e\",\n  \"best_result\": \"80054e2e\",\n  \"param_config\": \"80054e2e\",\n  \"extra_arg\": \"80054e2e\",\n  \"_state_json\": null,\n  \"_state_valid\": false\n}",
    "{\n  \"trainable_name\": \"training_function\",\n  \"trial_id\": \"01feb_00001\",\n  \"config\": {\n    \"layer_1_size\": 32,\n    \"layer_2_size\": 64,\n    \"lr\": 0.00019925487783813844,\n    \"batch_size\": 32\n  },\n  \"local_dir\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha\",\n  \"evaluated_params\": {\n    \"layer_1_size\": 32,\n    \"layer_2_size\": 64,\n    \"lr\": 0.00019925487783813844,\n    \"batch_size\": 32\n  },\n  \"experiment_tag\": \"1_batch_size=32,layer_1_size=32,layer_2_size=64,lr=0.00019925\",\n  \"location\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"8005953a000000000000008c0e7261792e74756e652e747269616c948c084c6f636174696f6e9493942981947d94288c08686f73746e616d65944e8c03706964944e75622e\"\n  },\n  \"resources\": {\n    \"cpu\": 6,\n    \"gpu\": 0,\n    \"memory\": 0,\n    \"object_store_memory\": 0,\n    \"extra_cpu\": 0,\n    \"extra_gpu\": 0,\n    \"extra_memory\": 0,\n    \"extra_object_store_memory\": 0,\n    \"custom_resources\": {},\n    \"extra_custom_resources\": {}\n  },\n  \"placement_group_factory\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"800595b2000000000000008c1f7261792e74756e652e7574696c732e706c6163656d656e745f67726f757073948c15506c6163656d656e7447726f7570466163746f72799493942981947d94288c085f62756e646c6573945d947d94288c03435055944b068c03475055944b008c066d656d6f7279944b008c136f626a6563745f73746f72655f6d656d6f7279944b0075618c095f7374726174656779948c045041434b948c055f6172677394298c075f6b7761726773947d9475622e\"\n  },\n  \"stopping_criterion\": {},\n  \"log_to_file\": [\n    null,\n    null\n  ],\n  \"max_failures\": 0,\n  \"last_result\": {},\n  \"last_update_time\": -Infinity,\n  \"metric_analysis\": {},\n  \"n_steps\": [\n    5,\n    10\n  ],\n  \"metric_n_steps\": {},\n  \"export_formats\": [],\n  \"status\": \"ERROR\",\n  \"start_time\": 1621847482.2748852,\n  \"logdir\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha/training_function_01feb_00001_1_batch_size=32,layer_1_size=32,layer_2_size=64,lr=0.00019925_2021-05-24_11-11-22\",\n  \"runner\": null,\n  \"last_debug\": 0,\n  \"error_file\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha/training_function_01feb_00001_1_batch_size=32,layer_1_size=32,layer_2_size=64,lr=0.00019925_2021-05-24_11-11-22/error.txt\",\n  \"error_msg\": \"Traceback (most recent call last):\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trial_runner.py\\\", line 702, in _process_trial\\n    results = self.trial_executor.fetch_result(trial)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py\\\", line 686, in fetch_result\\n    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/_private/client_mode_hook.py\\\", line 47, in wrapper\\n    return func(*args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/worker.py\\\", line 1481, in get\\n    raise value.as_instanceof_cause()\\nray.exceptions.RayTaskError(TuneError): \\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=52596, ip=192.168.2.103)\\n  File \\\"python/ray/_raylet.pyx\\\", line 505, in ray._raylet.execute_task\\n  File \\\"python/ray/_raylet.pyx\\\", line 449, in ray._raylet.execute_task.function_executor\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/_private/function_manager.py\\\", line 556, in actor_method_executor\\n    return method(__ray_actor, *args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trainable.py\\\", line 173, in train_buffered\\n    result = self.train()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trainable.py\\\", line 232, in train\\n    result = self.step()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 366, in step\\n    self._report_thread_runner_error(block=True)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 512, in _report_thread_runner_error\\n    raise TuneError(\\nray.tune.error.TuneError: Trial raised an exception. Traceback:\\n\\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=52596, ip=192.168.2.103)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 248, in run\\n    self._entrypoint()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 315, in entrypoint\\n    return self._trainable_func(self.config, self._status_reporter,\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 580, in _trainable_func\\n    output = fn()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/utils/trainable.py\\\", line 339, in _inner\\n    inner(config, checkpoint_dir=None)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/utils/trainable.py\\\", line 330, in inner\\n    trainable(config, **fn_kwargs)\\n  File \\\"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/src/Main.py\\\", line 32, in training_function\\n    trainer.fit(model)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 458, in fit\\n    self._run(model)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 756, in _run\\n    self.dispatch()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 797, in dispatch\\n    self.accelerator.start_training(self)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py\\\", line 96, in start_training\\n    self.training_type_plugin.start_training(trainer)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py\\\", line 144, in start_training\\n    self._results = trainer.run_stage()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 807, in run_stage\\n    return self.run_train()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 869, in run_train\\n    self.train_loop.run_training_epoch()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py\\\", line 489, in run_training_epoch\\n    batch_output = self.run_training_batch(batch, batch_idx, dataloader_idx)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py\\\", line 729, in run_training_batch\\n    self.optimizer_step(optimizer, opt_idx, batch_idx, train_step_and_backward_closure)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py\\\", line 424, in optimizer_step\\n    model_ref.optimizer_step(\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/core/lightning.py\\\", line 1403, in optimizer_step\\n    optimizer.step(closure=optimizer_closure)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/core/optimizer.py\\\", line 214, in step\\n    self.__optimizer_step(*args, closure=closure, profiler_name=profiler_name, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/core/optimizer.py\\\", line 134, in __optimizer_step\\n    trainer.accelerator.optimizer_step(optimizer, self._optimizer_idx, lambda_closure=closure, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py\\\", line 329, in optimizer_step\\n    self.run_optimizer_step(optimizer, opt_idx, lambda_closure, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py\\\", line 336, in run_optimizer_step\\n    self.training_type_plugin.optimizer_step(optimizer, lambda_closure=lambda_closure, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py\\\", line 193, in optimizer_step\\n    optimizer.step(closure=lambda_closure, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/torch/optim/optimizer.py\\\", line 89, in wrapper\\n    return func(*args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/torch/autograd/grad_mode.py\\\", line 27, in decorate_context\\n    return func(*args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/torch/optim/adam.py\\\", line 66, in step\\n    loss = closure()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py\\\", line 723, in train_step_and_backward_closure\\n    result = self.training_step_and_backward(\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py\\\", line 812, in training_step_and_backward\\n    result = self.training_step(split_batch, batch_idx, opt_idx, hiddens)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py\\\", line 280, in training_step\\n    training_step_output = self.trainer.accelerator.training_step(args)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py\\\", line 204, in training_step\\n    return self.training_type_plugin.training_step(*args)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py\\\", line 155, in training_step\\n    return self.lightning_module.training_step(*args, **kwargs)\\n  File \\\"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/src/models/LightningMNISTClassifier.py\\\", line 60, in training_step\\n    self.logger.experiment.logParam(self.layer_2_size) #.log_hyperparams(self.layer_1_size)\\nAttributeError: 'MlflowClient' object has no attribute 'logParam'\\n\",\n  \"trial_name_creator\": null,\n  \"custom_trial_name\": null,\n  \"custom_dirname\": null,\n  \"saving_to\": null,\n  \"remote_checkpoint_dir_prefix\": null,\n  \"checkpoint_freq\": 0,\n  \"checkpoint_at_end\": false,\n  \"keep_checkpoints_num\": null,\n  \"checkpoint_score_attr\": \"training_iteration\",\n  \"sync_on_checkpoint\": true,\n  \"checkpoint_manager\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"80059566010000000000008c1b7261792e74756e652e636865636b706f696e745f6d616e61676572948c11436865636b706f696e744d616e616765729493942981947d94288c146b6565705f636865636b706f696e74735f6e756d94477ff00000000000008c165f636865636b706f696e745f73636f72655f6465736394898c165f636865636b706f696e745f73636f72655f61747472948c12747261696e696e675f697465726174696f6e948c1c6e65776573745f70657273697374656e745f636865636b706f696e749468008c0a436865636b706f696e749493942981947d94288c0773746f72616765948c0a70657273697374656e74948c0576616c7565944e8c06726573756c74947d9475628c195f6e65776573745f6d656d6f72795f636865636b706f696e7494680b2981947d9428680e8c066d656d6f72799468104e68117d9475628c115f626573745f636865636b706f696e7473945d948c0b5f6d656d62657273686970948f9475622e\"\n  },\n  \"restore_path\": null,\n  \"restoring_from\": null,\n  \"num_failures\": 1,\n  \"results\": \"80054e2e\",\n  \"best_result\": \"80054e2e\",\n  \"param_config\": \"80054e2e\",\n  \"extra_arg\": \"80054e2e\",\n  \"_state_json\": null,\n  \"_state_valid\": false\n}",
    "{\n  \"trainable_name\": \"training_function\",\n  \"trial_id\": \"01feb_00004\",\n  \"config\": {\n    \"layer_1_size\": 32,\n    \"layer_2_size\": 64,\n    \"lr\": 0.006083783564069698,\n    \"batch_size\": 64\n  },\n  \"local_dir\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha\",\n  \"evaluated_params\": {\n    \"layer_1_size\": 32,\n    \"layer_2_size\": 64,\n    \"lr\": 0.006083783564069698,\n    \"batch_size\": 64\n  },\n  \"experiment_tag\": \"4_batch_size=64,layer_1_size=32,layer_2_size=64,lr=0.0060838\",\n  \"location\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"8005953a000000000000008c0e7261792e74756e652e747269616c948c084c6f636174696f6e9493942981947d94288c08686f73746e616d65944e8c03706964944e75622e\"\n  },\n  \"resources\": {\n    \"cpu\": 6,\n    \"gpu\": 0,\n    \"memory\": 0,\n    \"object_store_memory\": 0,\n    \"extra_cpu\": 0,\n    \"extra_gpu\": 0,\n    \"extra_memory\": 0,\n    \"extra_object_store_memory\": 0,\n    \"custom_resources\": {},\n    \"extra_custom_resources\": {}\n  },\n  \"placement_group_factory\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"800595b2000000000000008c1f7261792e74756e652e7574696c732e706c6163656d656e745f67726f757073948c15506c6163656d656e7447726f7570466163746f72799493942981947d94288c085f62756e646c6573945d947d94288c03435055944b068c03475055944b008c066d656d6f7279944b008c136f626a6563745f73746f72655f6d656d6f7279944b0075618c095f7374726174656779948c045041434b948c055f6172677394298c075f6b7761726773947d9475622e\"\n  },\n  \"stopping_criterion\": {},\n  \"log_to_file\": [\n    null,\n    null\n  ],\n  \"max_failures\": 0,\n  \"last_result\": {},\n  \"last_update_time\": -Infinity,\n  \"metric_analysis\": {},\n  \"n_steps\": [\n    5,\n    10\n  ],\n  \"metric_n_steps\": {},\n  \"export_formats\": [],\n  \"status\": \"ERROR\",\n  \"start_time\": 1621847498.74703,\n  \"logdir\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha/training_function_01feb_00004_4_batch_size=64,layer_1_size=32,layer_2_size=64,lr=0.0060838_2021-05-24_11-11-30\",\n  \"runner\": null,\n  \"last_debug\": 0,\n  \"error_file\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha/training_function_01feb_00004_4_batch_size=64,layer_1_size=32,layer_2_size=64,lr=0.0060838_2021-05-24_11-11-30/error.txt\",\n  \"error_msg\": \"Traceback (most recent call last):\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trial_runner.py\\\", line 702, in _process_trial\\n    results = self.trial_executor.fetch_result(trial)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py\\\", line 686, in fetch_result\\n    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/_private/client_mode_hook.py\\\", line 47, in wrapper\\n    return func(*args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/worker.py\\\", line 1481, in get\\n    raise value.as_instanceof_cause()\\nray.exceptions.RayTaskError(TuneError): \\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=52601, ip=192.168.2.103)\\n  File \\\"python/ray/_raylet.pyx\\\", line 505, in ray._raylet.execute_task\\n  File \\\"python/ray/_raylet.pyx\\\", line 449, in ray._raylet.execute_task.function_executor\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/_private/function_manager.py\\\", line 556, in actor_method_executor\\n    return method(__ray_actor, *args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trainable.py\\\", line 173, in train_buffered\\n    result = self.train()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trainable.py\\\", line 232, in train\\n    result = self.step()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 366, in step\\n    self._report_thread_runner_error(block=True)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 512, in _report_thread_runner_error\\n    raise TuneError(\\nray.tune.error.TuneError: Trial raised an exception. Traceback:\\n\\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=52601, ip=192.168.2.103)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 248, in run\\n    self._entrypoint()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 315, in entrypoint\\n    return self._trainable_func(self.config, self._status_reporter,\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 580, in _trainable_func\\n    output = fn()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/utils/trainable.py\\\", line 339, in _inner\\n    inner(config, checkpoint_dir=None)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/utils/trainable.py\\\", line 330, in inner\\n    trainable(config, **fn_kwargs)\\n  File \\\"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/src/Main.py\\\", line 32, in training_function\\n    trainer.fit(model)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 458, in fit\\n    self._run(model)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 756, in _run\\n    self.dispatch()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 797, in dispatch\\n    self.accelerator.start_training(self)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py\\\", line 96, in start_training\\n    self.training_type_plugin.start_training(trainer)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py\\\", line 144, in start_training\\n    self._results = trainer.run_stage()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 807, in run_stage\\n    return self.run_train()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 869, in run_train\\n    self.train_loop.run_training_epoch()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py\\\", line 489, in run_training_epoch\\n    batch_output = self.run_training_batch(batch, batch_idx, dataloader_idx)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py\\\", line 729, in run_training_batch\\n    self.optimizer_step(optimizer, opt_idx, batch_idx, train_step_and_backward_closure)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py\\\", line 424, in optimizer_step\\n    model_ref.optimizer_step(\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/core/lightning.py\\\", line 1403, in optimizer_step\\n    optimizer.step(closure=optimizer_closure)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/core/optimizer.py\\\", line 214, in step\\n    self.__optimizer_step(*args, closure=closure, profiler_name=profiler_name, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/core/optimizer.py\\\", line 134, in __optimizer_step\\n    trainer.accelerator.optimizer_step(optimizer, self._optimizer_idx, lambda_closure=closure, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py\\\", line 329, in optimizer_step\\n    self.run_optimizer_step(optimizer, opt_idx, lambda_closure, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py\\\", line 336, in run_optimizer_step\\n    self.training_type_plugin.optimizer_step(optimizer, lambda_closure=lambda_closure, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py\\\", line 193, in optimizer_step\\n    optimizer.step(closure=lambda_closure, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/torch/optim/optimizer.py\\\", line 89, in wrapper\\n    return func(*args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/torch/autograd/grad_mode.py\\\", line 27, in decorate_context\\n    return func(*args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/torch/optim/adam.py\\\", line 66, in step\\n    loss = closure()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py\\\", line 723, in train_step_and_backward_closure\\n    result = self.training_step_and_backward(\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py\\\", line 812, in training_step_and_backward\\n    result = self.training_step(split_batch, batch_idx, opt_idx, hiddens)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py\\\", line 280, in training_step\\n    training_step_output = self.trainer.accelerator.training_step(args)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py\\\", line 204, in training_step\\n    return self.training_type_plugin.training_step(*args)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py\\\", line 155, in training_step\\n    return self.lightning_module.training_step(*args, **kwargs)\\n  File \\\"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/src/models/LightningMNISTClassifier.py\\\", line 60, in training_step\\n    self.logger.experiment.logParam(self.layer_2_size) #.log_hyperparams(self.layer_1_size)\\nAttributeError: 'MlflowClient' object has no attribute 'logParam'\\n\",\n  \"trial_name_creator\": null,\n  \"custom_trial_name\": null,\n  \"custom_dirname\": null,\n  \"saving_to\": null,\n  \"remote_checkpoint_dir_prefix\": null,\n  \"checkpoint_freq\": 0,\n  \"checkpoint_at_end\": false,\n  \"keep_checkpoints_num\": null,\n  \"checkpoint_score_attr\": \"training_iteration\",\n  \"sync_on_checkpoint\": true,\n  \"checkpoint_manager\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"80059566010000000000008c1b7261792e74756e652e636865636b706f696e745f6d616e61676572948c11436865636b706f696e744d616e616765729493942981947d94288c146b6565705f636865636b706f696e74735f6e756d94477ff00000000000008c165f636865636b706f696e745f73636f72655f6465736394898c165f636865636b706f696e745f73636f72655f61747472948c12747261696e696e675f697465726174696f6e948c1c6e65776573745f70657273697374656e745f636865636b706f696e749468008c0a436865636b706f696e749493942981947d94288c0773746f72616765948c0a70657273697374656e74948c0576616c7565944e8c06726573756c74947d9475628c195f6e65776573745f6d656d6f72795f636865636b706f696e7494680b2981947d9428680e8c066d656d6f72799468104e68117d9475628c115f626573745f636865636b706f696e7473945d948c0b5f6d656d62657273686970948f9475622e\"\n  },\n  \"restore_path\": null,\n  \"restoring_from\": null,\n  \"num_failures\": 1,\n  \"results\": \"80054e2e\",\n  \"best_result\": \"80054e2e\",\n  \"param_config\": \"80054e2e\",\n  \"extra_arg\": \"80054e2e\",\n  \"_state_json\": null,\n  \"_state_valid\": false\n}",
    "{\n  \"trainable_name\": \"training_function\",\n  \"trial_id\": \"01feb_00006\",\n  \"config\": {\n    \"layer_1_size\": 64,\n    \"layer_2_size\": 256,\n    \"lr\": 0.017117039785516104,\n    \"batch_size\": 64\n  },\n  \"local_dir\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha\",\n  \"evaluated_params\": {\n    \"layer_1_size\": 64,\n    \"layer_2_size\": 256,\n    \"lr\": 0.017117039785516104,\n    \"batch_size\": 64\n  },\n  \"experiment_tag\": \"6_batch_size=64,layer_1_size=64,layer_2_size=256,lr=0.017117\",\n  \"location\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"8005953a000000000000008c0e7261792e74756e652e747269616c948c084c6f636174696f6e9493942981947d94288c08686f73746e616d65944e8c03706964944e75622e\"\n  },\n  \"resources\": {\n    \"cpu\": 6,\n    \"gpu\": 0,\n    \"memory\": 0,\n    \"object_store_memory\": 0,\n    \"extra_cpu\": 0,\n    \"extra_gpu\": 0,\n    \"extra_memory\": 0,\n    \"extra_object_store_memory\": 0,\n    \"custom_resources\": {},\n    \"extra_custom_resources\": {}\n  },\n  \"placement_group_factory\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"800595b2000000000000008c1f7261792e74756e652e7574696c732e706c6163656d656e745f67726f757073948c15506c6163656d656e7447726f7570466163746f72799493942981947d94288c085f62756e646c6573945d947d94288c03435055944b068c03475055944b008c066d656d6f7279944b008c136f626a6563745f73746f72655f6d656d6f7279944b0075618c095f7374726174656779948c045041434b948c055f6172677394298c075f6b7761726773947d9475622e\"\n  },\n  \"stopping_criterion\": {},\n  \"log_to_file\": [\n    null,\n    null\n  ],\n  \"max_failures\": 0,\n  \"last_result\": {},\n  \"last_update_time\": -Infinity,\n  \"metric_analysis\": {},\n  \"n_steps\": [\n    5,\n    10\n  ],\n  \"metric_n_steps\": {},\n  \"export_formats\": [],\n  \"status\": \"ERROR\",\n  \"start_time\": 1621847506.922291,\n  \"logdir\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha/training_function_01feb_00006_6_batch_size=64,layer_1_size=64,layer_2_size=256,lr=0.017117_2021-05-24_11-11-38\",\n  \"runner\": null,\n  \"last_debug\": 0,\n  \"error_file\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha/training_function_01feb_00006_6_batch_size=64,layer_1_size=64,layer_2_size=256,lr=0.017117_2021-05-24_11-11-38/error.txt\",\n  \"error_msg\": \"Traceback (most recent call last):\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trial_runner.py\\\", line 702, in _process_trial\\n    results = self.trial_executor.fetch_result(trial)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py\\\", line 686, in fetch_result\\n    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/_private/client_mode_hook.py\\\", line 47, in wrapper\\n    return func(*args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/worker.py\\\", line 1481, in get\\n    raise value.as_instanceof_cause()\\nray.exceptions.RayTaskError(TuneError): \\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=52591, ip=192.168.2.103)\\n  File \\\"python/ray/_raylet.pyx\\\", line 505, in ray._raylet.execute_task\\n  File \\\"python/ray/_raylet.pyx\\\", line 449, in ray._raylet.execute_task.function_executor\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/_private/function_manager.py\\\", line 556, in actor_method_executor\\n    return method(__ray_actor, *args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trainable.py\\\", line 173, in train_buffered\\n    result = self.train()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trainable.py\\\", line 232, in train\\n    result = self.step()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 366, in step\\n    self._report_thread_runner_error(block=True)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 512, in _report_thread_runner_error\\n    raise TuneError(\\nray.tune.error.TuneError: Trial raised an exception. Traceback:\\n\\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=52591, ip=192.168.2.103)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 248, in run\\n    self._entrypoint()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 315, in entrypoint\\n    return self._trainable_func(self.config, self._status_reporter,\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 580, in _trainable_func\\n    output = fn()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/utils/trainable.py\\\", line 339, in _inner\\n    inner(config, checkpoint_dir=None)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/utils/trainable.py\\\", line 330, in inner\\n    trainable(config, **fn_kwargs)\\n  File \\\"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/src/Main.py\\\", line 32, in training_function\\n    trainer.fit(model)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 458, in fit\\n    self._run(model)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 756, in _run\\n    self.dispatch()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 797, in dispatch\\n    self.accelerator.start_training(self)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py\\\", line 96, in start_training\\n    self.training_type_plugin.start_training(trainer)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py\\\", line 144, in start_training\\n    self._results = trainer.run_stage()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 807, in run_stage\\n    return self.run_train()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 869, in run_train\\n    self.train_loop.run_training_epoch()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py\\\", line 489, in run_training_epoch\\n    batch_output = self.run_training_batch(batch, batch_idx, dataloader_idx)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py\\\", line 729, in run_training_batch\\n    self.optimizer_step(optimizer, opt_idx, batch_idx, train_step_and_backward_closure)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py\\\", line 424, in optimizer_step\\n    model_ref.optimizer_step(\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/core/lightning.py\\\", line 1403, in optimizer_step\\n    optimizer.step(closure=optimizer_closure)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/core/optimizer.py\\\", line 214, in step\\n    self.__optimizer_step(*args, closure=closure, profiler_name=profiler_name, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/core/optimizer.py\\\", line 134, in __optimizer_step\\n    trainer.accelerator.optimizer_step(optimizer, self._optimizer_idx, lambda_closure=closure, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py\\\", line 329, in optimizer_step\\n    self.run_optimizer_step(optimizer, opt_idx, lambda_closure, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py\\\", line 336, in run_optimizer_step\\n    self.training_type_plugin.optimizer_step(optimizer, lambda_closure=lambda_closure, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py\\\", line 193, in optimizer_step\\n    optimizer.step(closure=lambda_closure, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/torch/optim/optimizer.py\\\", line 89, in wrapper\\n    return func(*args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/torch/autograd/grad_mode.py\\\", line 27, in decorate_context\\n    return func(*args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/torch/optim/adam.py\\\", line 66, in step\\n    loss = closure()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py\\\", line 723, in train_step_and_backward_closure\\n    result = self.training_step_and_backward(\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py\\\", line 812, in training_step_and_backward\\n    result = self.training_step(split_batch, batch_idx, opt_idx, hiddens)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py\\\", line 280, in training_step\\n    training_step_output = self.trainer.accelerator.training_step(args)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py\\\", line 204, in training_step\\n    return self.training_type_plugin.training_step(*args)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py\\\", line 155, in training_step\\n    return self.lightning_module.training_step(*args, **kwargs)\\n  File \\\"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/src/models/LightningMNISTClassifier.py\\\", line 60, in training_step\\n    self.logger.experiment.logParam(self.layer_2_size) #.log_hyperparams(self.layer_1_size)\\nAttributeError: 'MlflowClient' object has no attribute 'logParam'\\n\",\n  \"trial_name_creator\": null,\n  \"custom_trial_name\": null,\n  \"custom_dirname\": null,\n  \"saving_to\": null,\n  \"remote_checkpoint_dir_prefix\": null,\n  \"checkpoint_freq\": 0,\n  \"checkpoint_at_end\": false,\n  \"keep_checkpoints_num\": null,\n  \"checkpoint_score_attr\": \"training_iteration\",\n  \"sync_on_checkpoint\": true,\n  \"checkpoint_manager\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"80059566010000000000008c1b7261792e74756e652e636865636b706f696e745f6d616e61676572948c11436865636b706f696e744d616e616765729493942981947d94288c146b6565705f636865636b706f696e74735f6e756d94477ff00000000000008c165f636865636b706f696e745f73636f72655f6465736394898c165f636865636b706f696e745f73636f72655f61747472948c12747261696e696e675f697465726174696f6e948c1c6e65776573745f70657273697374656e745f636865636b706f696e749468008c0a436865636b706f696e749493942981947d94288c0773746f72616765948c0a70657273697374656e74948c0576616c7565944e8c06726573756c74947d9475628c195f6e65776573745f6d656d6f72795f636865636b706f696e7494680b2981947d9428680e8c066d656d6f72799468104e68117d9475628c115f626573745f636865636b706f696e7473945d948c0b5f6d656d62657273686970948f9475622e\"\n  },\n  \"restore_path\": null,\n  \"restoring_from\": null,\n  \"num_failures\": 1,\n  \"results\": \"80054e2e\",\n  \"best_result\": \"80054e2e\",\n  \"param_config\": \"80054e2e\",\n  \"extra_arg\": \"80054e2e\",\n  \"_state_json\": null,\n  \"_state_valid\": false\n}",
    "{\n  \"trainable_name\": \"training_function\",\n  \"trial_id\": \"01feb_00008\",\n  \"config\": {\n    \"layer_1_size\": 128,\n    \"layer_2_size\": 128,\n    \"lr\": 0.011809453878475772,\n    \"batch_size\": 32\n  },\n  \"local_dir\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha\",\n  \"evaluated_params\": {\n    \"layer_1_size\": 128,\n    \"layer_2_size\": 128,\n    \"lr\": 0.011809453878475772,\n    \"batch_size\": 32\n  },\n  \"experiment_tag\": \"8_batch_size=32,layer_1_size=128,layer_2_size=128,lr=0.011809\",\n  \"location\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"8005953a000000000000008c0e7261792e74756e652e747269616c948c084c6f636174696f6e9493942981947d94288c08686f73746e616d65944e8c03706964944e75622e\"\n  },\n  \"resources\": {\n    \"cpu\": 6,\n    \"gpu\": 0,\n    \"memory\": 0,\n    \"object_store_memory\": 0,\n    \"extra_cpu\": 0,\n    \"extra_gpu\": 0,\n    \"extra_memory\": 0,\n    \"extra_object_store_memory\": 0,\n    \"custom_resources\": {},\n    \"extra_custom_resources\": {}\n  },\n  \"placement_group_factory\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"800595b2000000000000008c1f7261792e74756e652e7574696c732e706c6163656d656e745f67726f757073948c15506c6163656d656e7447726f7570466163746f72799493942981947d94288c085f62756e646c6573945d947d94288c03435055944b068c03475055944b008c066d656d6f7279944b008c136f626a6563745f73746f72655f6d656d6f7279944b0075618c095f7374726174656779948c045041434b948c055f6172677394298c075f6b7761726773947d9475622e\"\n  },\n  \"stopping_criterion\": {},\n  \"log_to_file\": [\n    null,\n    null\n  ],\n  \"max_failures\": 0,\n  \"last_result\": {},\n  \"last_update_time\": -Infinity,\n  \"metric_analysis\": {},\n  \"n_steps\": [\n    5,\n    10\n  ],\n  \"metric_n_steps\": {},\n  \"export_formats\": [],\n  \"status\": \"ERROR\",\n  \"start_time\": 1621847515.261378,\n  \"logdir\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha/training_function_01feb_00008_8_batch_size=32,layer_1_size=128,layer_2_size=128,lr=0.011809_2021-05-24_11-11-46\",\n  \"runner\": null,\n  \"last_debug\": 0,\n  \"error_file\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha/training_function_01feb_00008_8_batch_size=32,layer_1_size=128,layer_2_size=128,lr=0.011809_2021-05-24_11-11-46/error.txt\",\n  \"error_msg\": \"Traceback (most recent call last):\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trial_runner.py\\\", line 702, in _process_trial\\n    results = self.trial_executor.fetch_result(trial)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py\\\", line 686, in fetch_result\\n    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/_private/client_mode_hook.py\\\", line 47, in wrapper\\n    return func(*args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/worker.py\\\", line 1481, in get\\n    raise value.as_instanceof_cause()\\nray.exceptions.RayTaskError(TuneError): \\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=52595, ip=192.168.2.103)\\n  File \\\"python/ray/_raylet.pyx\\\", line 505, in ray._raylet.execute_task\\n  File \\\"python/ray/_raylet.pyx\\\", line 449, in ray._raylet.execute_task.function_executor\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/_private/function_manager.py\\\", line 556, in actor_method_executor\\n    return method(__ray_actor, *args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trainable.py\\\", line 173, in train_buffered\\n    result = self.train()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trainable.py\\\", line 232, in train\\n    result = self.step()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 366, in step\\n    self._report_thread_runner_error(block=True)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 512, in _report_thread_runner_error\\n    raise TuneError(\\nray.tune.error.TuneError: Trial raised an exception. Traceback:\\n\\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=52595, ip=192.168.2.103)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 248, in run\\n    self._entrypoint()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 315, in entrypoint\\n    return self._trainable_func(self.config, self._status_reporter,\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 580, in _trainable_func\\n    output = fn()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/utils/trainable.py\\\", line 339, in _inner\\n    inner(config, checkpoint_dir=None)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/utils/trainable.py\\\", line 330, in inner\\n    trainable(config, **fn_kwargs)\\n  File \\\"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/src/Main.py\\\", line 32, in training_function\\n    trainer.fit(model)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 458, in fit\\n    self._run(model)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 756, in _run\\n    self.dispatch()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 797, in dispatch\\n    self.accelerator.start_training(self)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py\\\", line 96, in start_training\\n    self.training_type_plugin.start_training(trainer)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py\\\", line 144, in start_training\\n    self._results = trainer.run_stage()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 807, in run_stage\\n    return self.run_train()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 869, in run_train\\n    self.train_loop.run_training_epoch()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py\\\", line 489, in run_training_epoch\\n    batch_output = self.run_training_batch(batch, batch_idx, dataloader_idx)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py\\\", line 729, in run_training_batch\\n    self.optimizer_step(optimizer, opt_idx, batch_idx, train_step_and_backward_closure)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py\\\", line 424, in optimizer_step\\n    model_ref.optimizer_step(\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/core/lightning.py\\\", line 1403, in optimizer_step\\n    optimizer.step(closure=optimizer_closure)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/core/optimizer.py\\\", line 214, in step\\n    self.__optimizer_step(*args, closure=closure, profiler_name=profiler_name, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/core/optimizer.py\\\", line 134, in __optimizer_step\\n    trainer.accelerator.optimizer_step(optimizer, self._optimizer_idx, lambda_closure=closure, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py\\\", line 329, in optimizer_step\\n    self.run_optimizer_step(optimizer, opt_idx, lambda_closure, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py\\\", line 336, in run_optimizer_step\\n    self.training_type_plugin.optimizer_step(optimizer, lambda_closure=lambda_closure, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py\\\", line 193, in optimizer_step\\n    optimizer.step(closure=lambda_closure, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/torch/optim/optimizer.py\\\", line 89, in wrapper\\n    return func(*args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/torch/autograd/grad_mode.py\\\", line 27, in decorate_context\\n    return func(*args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/torch/optim/adam.py\\\", line 66, in step\\n    loss = closure()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py\\\", line 723, in train_step_and_backward_closure\\n    result = self.training_step_and_backward(\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py\\\", line 812, in training_step_and_backward\\n    result = self.training_step(split_batch, batch_idx, opt_idx, hiddens)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py\\\", line 280, in training_step\\n    training_step_output = self.trainer.accelerator.training_step(args)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py\\\", line 204, in training_step\\n    return self.training_type_plugin.training_step(*args)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py\\\", line 155, in training_step\\n    return self.lightning_module.training_step(*args, **kwargs)\\n  File \\\"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/src/models/LightningMNISTClassifier.py\\\", line 60, in training_step\\n    self.logger.experiment.logParam(self.layer_2_size) #.log_hyperparams(self.layer_1_size)\\nAttributeError: 'MlflowClient' object has no attribute 'logParam'\\n\",\n  \"trial_name_creator\": null,\n  \"custom_trial_name\": null,\n  \"custom_dirname\": null,\n  \"saving_to\": null,\n  \"remote_checkpoint_dir_prefix\": null,\n  \"checkpoint_freq\": 0,\n  \"checkpoint_at_end\": false,\n  \"keep_checkpoints_num\": null,\n  \"checkpoint_score_attr\": \"training_iteration\",\n  \"sync_on_checkpoint\": true,\n  \"checkpoint_manager\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"80059566010000000000008c1b7261792e74756e652e636865636b706f696e745f6d616e61676572948c11436865636b706f696e744d616e616765729493942981947d94288c146b6565705f636865636b706f696e74735f6e756d94477ff00000000000008c165f636865636b706f696e745f73636f72655f6465736394898c165f636865636b706f696e745f73636f72655f61747472948c12747261696e696e675f697465726174696f6e948c1c6e65776573745f70657273697374656e745f636865636b706f696e749468008c0a436865636b706f696e749493942981947d94288c0773746f72616765948c0a70657273697374656e74948c0576616c7565944e8c06726573756c74947d9475628c195f6e65776573745f6d656d6f72795f636865636b706f696e7494680b2981947d9428680e8c066d656d6f72799468104e68117d9475628c115f626573745f636865636b706f696e7473945d948c0b5f6d656d62657273686970948f9475622e\"\n  },\n  \"restore_path\": null,\n  \"restoring_from\": null,\n  \"num_failures\": 1,\n  \"results\": \"80054e2e\",\n  \"best_result\": \"80054e2e\",\n  \"param_config\": \"80054e2e\",\n  \"extra_arg\": \"80054e2e\",\n  \"_state_json\": null,\n  \"_state_valid\": false\n}"
  ],
  "runner_data": {
    "_max_pending_trials": 1000,
    "_metric": "loss",
    "_total_time": 0,
    "_iteration": 116,
    "_has_errored": true,
    "_fail_fast": false,
    "_server_port": null,
    "_cached_trial_decisions": {},
    "_queued_trial_decisions": {},
    "_updated_queue": true,
    "_should_stop_experiment": false,
    "_local_checkpoint_dir": "/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha",
    "_remote_checkpoint_dir": null,
    "_stopper": {
      "_type": "CLOUDPICKLE_FALLBACK",
      "value": "80059527000000000000008c107261792e74756e652e73746f70706572948c0b4e6f6f7053746f707065729493942981942e"
    },
    "_resumed": false,
    "_start_time": 1621847482.0992808,
    "_last_checkpoint_time": -Infinity,
    "_session_str": "2021-05-24_11-11-22",
    "checkpoint_file": "/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha/experiment_state-2021-05-24_11-11-22.json",
    "_checkpoint_period": "auto",
    "launch_web_server": false
  },
  "stats": {
    "start_time": 1621847482.0992808,
    "timestamp": 1621847523.881073
  }
}